# Generated by Django 5.0.7 on 2024-08-05 21:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('comentarios', models.TextField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('precio_venta', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('A', 'Audifonos'), ('L', 'Laptop'), ('M', 'Mobiles'), ('T', 'Teclados')], max_length=50)),
                ('imagen_producto', models.ImageField(upload_to='imagenproducto')),
            ],
            options={
                'verbose_name_plural': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.IntegerField()),
                ('region', models.CharField(choices=[('I\tRegión de Tarapacá', 'I\tRegión de Tarapacá'), ('II Región de Antofagasta', 'II Región de Antofagasta'), ('III Región de Atacama', 'III Región de Atacama'), ('IV Región de Coquimbo', 'IV Región de Coquimbo'), ('V Región de Valparaíso', 'V Región de Valparaíso'), ('VI Región del Libertador General Bernardo OHiggins', 'VI Región del Libertador General Bernardo OHiggins'), ('VII Región del Maule', 'VII Región del Maule'), ('VIII Región del Bio-bío', 'VIII Región del Bio-bío'), ('IX Región de La Araucanía', 'IX Región de La Araucanía'), ('X Región de Los Lagos', 'X Región de Los Lagos'), ('XI Región Aysén del General Carlos Ibáñez del Campo', 'XI Región Aysén del General Carlos Ibáñez del Campo'), ('XII Región de Magallanes y Antártica Chilena', 'XII Región de Magallanes y Antártica Chilena'), ('Región Metropolitana de Santiago', 'Región Metropolitana de Santiago'), ('XIV Región de Los Ríos', 'XIV Región de Los Ríos'), ('XV Región de Arica y Parinacota', 'XV Región de Arica y Parinacota'), ('XVI Región de Ñuble', 'XVI Región de Ñuble')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='PedidoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Aceptado', 'Aceptado'), ('Empacado', 'Empacado'), ('En camino', 'En camino'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Aceptado', max_length=100)),
                ('precio_producto', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
            options={
                'verbose_name_plural': 'Pedido Realizado',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
            options={
                'verbose_name_plural': 'Carrito',
            },
        ),
    ]
